# -*- coding: utf-8 -*-
"""Dashboard_Mantenimiento_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WBfGFEJRU6TocBQtpyFb3ttSjgUCEBi

# 📊 Dashboard Interactivo de Mantenimiento
Este dashboard visualiza datos históricos de órdenes de trabajo para detectar patrones, identificar equipos críticos y apoyar la toma de decisiones.
"""

# 📦 Librerías necesarias
import pandas as pd
import plotly.express as px
from google.colab import files
from datetime import datetime

# 📁 Subir el archivo CSV
uploaded = files.upload()
df = pd.read_csv(next(iter(uploaded)), encoding='latin-1')
df['Fecha'] = pd.to_datetime(df['Fecha'], errors='coerce')
df.dropna(subset=['Fecha'], inplace=True)
df.head()

# @title Tiempo de paro (h)

from matplotlib import pyplot as plt
df['Tiempo de paro (h)'].plot(kind='hist', bins=20, title='Tiempo de paro (h)')
plt.gca().spines[['top', 'right',]].set_visible(False)

# 🧼 Limpieza opcional (asegurar nombres de columnas)
df.columns = df.columns.str.strip()
df['Mes'] = df['Fecha'].dt.to_period('M')
df['Año'] = df['Fecha'].dt.year

"""## 🔧 Fallas por componente"""

fig1 = px.histogram(df, x='Componente', color='Equipo', title='Fallas por componente',
                   category_orders={'Componente': df['Componente'].value_counts().index.tolist()})
fig1.show()

"""## 🏭 Equipos con más fallas"""

fig2 = px.histogram(df, x='Equipo', title='Ranking de equipos con más fallas',
                   category_orders={'Equipo': df['Equipo'].value_counts().index.tolist()})
fig2.show()

"""## 📅 Tendencia mensual de fallas"""

fallas_mes = df.groupby('Mes').size().reset_index(name='Fallas')
fig3 = px.line(fallas_mes, x='Mes', y='Fallas', title='Evolución de fallas por mes')
fig3.show()

"""## ⏱️ Tiempo entre fallos (simplificado)"""

df_sorted = df.sort_values(by=['Equipo', 'Fecha'])
df_sorted['Tiempo_entre_fallas'] = df_sorted.groupby('Equipo')['Fecha'].diff().dt.days
df_sorted[['Equipo', 'Fecha', 'Tiempo_entre_fallas']].dropna().head(10)